<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sss" nsURI="http://srg.aut.uah.es/micobs/svm/sss" nsPrefix="svm">
  <eClassifiers xsi:type="ecore:EClass" name="VSSSIntroduction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purpose" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objetive" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSApplicableDocuments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocument" upperBound="-1"
        eType="#//VSSSApplicableDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSApplicableDocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSReferenceDocuments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocuments" upperBound="-1"
        eType="#//VSSSReferenceDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSReferenceDocument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSTermsDefinitionsAbbreviations">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="term" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abbreviation" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSGeneralDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productPerspective" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generalCapabilites" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generalConstraints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationalEnvironment"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assumptionsDependencies"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSpecificRequirements" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" upperBound="-1"
        eType="#//VSSSGeneralDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilities" upperBound="-1"
        eType="#//VSSSCapabilitiesRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInterface" upperBound="-1"
        eType="#//VSSSSystemInterfaceRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptationMissionization"
        upperBound="-1" eType="#//VSSSAdaptationMissionizationRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computerResource" upperBound="-1"
        eType="#//VSSSComputerResourceRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security" upperBound="-1"
        eType="#//VSSSSecurityRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safety" upperBound="-1"
        eType="#//VSSSSafetyRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reliabiltyAvailability"
        upperBound="-1" eType="#//VSSSReliabiltyAvailabilityRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality" upperBound="-1"
        eType="#//VSSSQualityRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="design" upperBound="-1"
        eType="#//VSSSDesignRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareOperations" upperBound="-1"
        eType="#//VSSSSoftwareOperationsRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareMaintenance" upperBound="-1"
        eType="#//VSSSSoftwareMaintenanceRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemSoftwareObservability"
        upperBound="-1" eType="#//VSSSSystemSoftwareObservabilityRequirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSGeneralRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSCapabilitiesRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemInterfaceRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSAdaptationMissionizationRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSComputerResourceRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSecurityRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSafetyRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSReliabiltyAvailabilityRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSQualityRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSDesignRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSoftwareOperationsRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSoftwareMaintenanceRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemSoftwareObservabilityRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationValidationIntegration"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationValidationProcess"
        upperBound="-1" eType="#//VSSSVerificationValidationProcessRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationApproach" upperBound="-1"
        eType="#//VSSSValidationApproach" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validation" upperBound="-1"
        eType="#//VSSSValidationRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verification" upperBound="-1"
        eType="#//VSSSVerificationRequirement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationValidationProcessRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSValidationApproach" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSValidationRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemModels">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemModel" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
