<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sss" nsURI="http://srg.aut.uah.es/micobs/svm/sss" nsPrefix="svm">
  <eClassifiers xsi:type="ecore:EClass" name="VSSSIntroduction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSPurpose" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSObjetive" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSContent" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSReason" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSApplicableDocuments">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSApplicableDocument"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSReferenceDocuments">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSReferenceDocument"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSTermsDefinitionsAbbreviations">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSTerm" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSDefinition" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSAbbreviation" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSGeneralDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSProductPerspective"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSGeneralCapabilites"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSGeneralConstraints"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSOperationalEnvironment"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VSSSAssumptionsDependencies"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSpecificRequirements" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" upperBound="-1"
        eType="#//VSSSGeneralDescription"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilities" upperBound="-1"
        eType="#//VSSSCapabilitiesRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInterface" upperBound="-1"
        eType="#//VSSSSystemInterfaceRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptationMissionization"
        upperBound="-1" eType="#//VSSSAdaptationMissionizationRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computerResource" upperBound="-1"
        eType="#//VSSSComputerResourceRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security" upperBound="-1"
        eType="#//VSSSSecurityRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safety" upperBound="-1"
        eType="#//VSSSSafetyRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reliabiltyAvailability"
        upperBound="-1" eType="#//VSSSReliabiltyAvailabilityRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality" upperBound="-1"
        eType="#//VSSSQualityRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="design" upperBound="-1"
        eType="#//VSSSDesignRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareOperations" upperBound="-1"
        eType="#//VSSSSoftwareOperationsRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareMaintenance" upperBound="-1"
        eType="#//VSSSSoftwareMaintenanceRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemSoftwareObservability"
        upperBound="-1" eType="#//VSSSSystemSoftwareObservabilityRequirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSGeneralRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSCapabilitiesRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemInterfaceRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSAdaptationMissionizationRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSComputerResourceRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSecurityRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSafetyRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSReliabiltyAvailabilityRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSQualityRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSDesignRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSoftwareOperationsRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSoftwareMaintenanceRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemSoftwareObservabilityRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationValidationIntegration"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationValidationProcess"
        upperBound="-1" eType="#//VSSSVerificationValidationProcessRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationApproach" upperBound="-1"
        eType="#//VSSSValidationApproach"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validation" upperBound="-1"
        eType="#//VSSSValidationRequirement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verification" upperBound="-1"
        eType="#//VSSSVerificationRequirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationValidationProcessRequirement"
      eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSValidationApproach" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSValidationRequirement" eSuperTypes="tdm.ecore#//VTraceableDocumentFixedGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemModels">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemModel" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
