<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sss" nsURI="http://srg.aut.uah.es/micobs/svm/sss" nsPrefix="micobs.svm">
  <eClassifiers xsi:type="ecore:EClass" name="VSSSDocument" eSuperTypes="tdm.ecore#//VTraceableDocument ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DDocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="introductionSection" lowerBound="1"
        eType="#//VSSSIntroduction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocumentsSection"
        lowerBound="1" eType="#//VSSSApplicableDocuments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocumentsSection"
        lowerBound="1" eType="#//VSSSReferenceDocuments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="termsDefinitionsAbbreviationsSection"
        lowerBound="1" eType="#//VSSSTermsDefinitionsAbbreviations" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalDescriptionSection"
        lowerBound="1" eType="#//VSSSGeneralDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificRequirementsSection"
        lowerBound="1" eType="#//VSSSSpecificRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationValidationIntegrationSection"
        lowerBound="1" eType="#//VSSSVerificationValidationIntegrationRequirements"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemModelsSection" lowerBound="1"
        eType="#//VSSSSystemModels" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssFigures" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DAbstractFigure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssTables" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DAbstractTable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSIntroduction" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssInstatiableSubsections"
        lowerBound="1" upperBound="-1" eType="#//VSSSInstantiableSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSApplicableDocuments" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocuments" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DApplicableDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSReferenceDocuments" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocuments" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DReferenceDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSTermsDefinitionsAbbreviations" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1"
        eType="#//VSSSTerm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//VSSSDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abbreviations" upperBound="-1"
        eType="#//VSSSAbbreviation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSAbstractBriefDescription" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DRun"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSTerm" eSuperTypes="#//VSSSAbstractBriefDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSDefinition" eSuperTypes="#//VSSSAbstractBriefDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSAbbreviation" eSuperTypes="#//VSSSAbstractBriefDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSFixedSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssInstatiableSubsections"
        upperBound="-1" eType="#//VSSSInstantiableSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSInstantiableSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DInstantiableSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssInstatiableSubsections"
        upperBound="-1" eType="#//VSSSInstantiableSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSGeneralDescription" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="productPerspective" lowerBound="1"
        eType="#//VSSSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalCapabilities" lowerBound="1"
        eType="#//VSSSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalConstraints" lowerBound="1"
        eType="#//VSSSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationalEnvironment"
        lowerBound="1" eType="#//VSSSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assumptionsDependencies"
        lowerBound="1" eType="#//VSSSFixedSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSAbstractRequirementSection" abstract="true"
      eSuperTypes="tdm.ecore#//VTraceableDocumentAbstractGroup ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectionDescription" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssItems" upperBound="-1"
        eType="#//VSSSDocumentItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssRequirementSubsections"
        upperBound="-1" eType="#//VSSSInstantiableRequirementSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSInstantiableRequirementSection"
      eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DInstantiableSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectionDescription" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sssItems" upperBound="-1"
        eType="#//VSSSDocumentItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSpecificRequirements" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectionDescription" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" lowerBound="1"
        eType="#//VSSSGeneralRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilities" lowerBound="1"
        eType="#//VSSSCapabilitiesRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemInterface" lowerBound="1"
        eType="#//VSSSSystemInterfaceRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptationMissionization"
        lowerBound="1" eType="#//VSSSAdaptationMissionizationRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computerResource" lowerBound="1"
        eType="#//VSSSComputerResourceRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security" lowerBound="1"
        eType="#//VSSSSecurityRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safety" lowerBound="1"
        eType="#//VSSSSafetyRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reliabiltyAvailability"
        lowerBound="1" eType="#//VSSSReliabiltyAvailabilityRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quality" lowerBound="1"
        eType="#//VSSSQualityRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="design" lowerBound="1"
        eType="#//VSSSDesignRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareOperations" lowerBound="1"
        eType="#//VSSSSoftwareOperationsRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareMaintenance" lowerBound="1"
        eType="#//VSSSSoftwareMaintenanceRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemSoftwareObservability"
        lowerBound="1" eType="#//VSSSSystemSoftwareObservabilityRequirements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSGeneralRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSCapabilitiesRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemInterfaceRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSAdaptationMissionizationRequirements"
      eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSComputerResourceRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSecurityRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSafetyRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSReliabiltyAvailabilityRequirements"
      eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSQualityRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSDesignRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSoftwareOperationsRequirements"
      eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSoftwareMaintenanceRequirements"
      eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemSoftwareObservabilityRequirements"
      eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationValidationIntegrationRequirements"
      eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectionDescription" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verificationValidationProcess"
        lowerBound="1" eType="#//VSSSVerificationValidationProcessRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validationApproach" lowerBound="1"
        eType="#//VSSSValidationApproach" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validation" lowerBound="1"
        eType="#//VSSSValidationRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verification" lowerBound="1"
        eType="#//VSSSVerificationRequirements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationValidationProcessRequirements"
      eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSValidationApproach" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSVerificationRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSValidationRequirements" eSuperTypes="#//VSSSAbstractRequirementSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSDocumentItem" eSuperTypes="tdm.ecore#//VTraceableDocumentAbstractItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedDescription" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemModels" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="systemModels" upperBound="-1"
        eType="#//VSSSSystemModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSSSSystemModel"/>
</ecore:EPackage>
