<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="svs" nsURI="http://srg.aut.uah.es/micobs/svm/svs" nsPrefix="micobs.svm">
  <eClassifiers xsi:type="ecore:EClass" name="VSVSDocument" eSuperTypes="vdm.ecore#//VValidationDocument ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DDocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="introductionSection" lowerBound="1"
        eType="#//VSVSIntroduction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocumentsSection"
        lowerBound="1" eType="#//VSVSApplicableDocuments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocumentsSection"
        lowerBound="1" eType="#//VSVSReferenceDocuments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="termsDefinitionsAbbreviationsSection"
        lowerBound="1" eType="#//VSVSTermsDefinitionsAbbreviations" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareOverviewSection"
        lowerBound="1" eType="#//VSVSSoftwareOverview" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskIdentificationSection"
        lowerBound="1" eType="#//VSVSTaskIdentification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testingSpecificationDesignSection"
        lowerBound="1" eType="#//VSVSTestingSpecificationDesign" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCasesSection" lowerBound="1"
        eType="#//VSVSTestCases" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testProceduresSection"
        lowerBound="1" eType="#//VSVSTestProcedures" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analysisInspectionReviewSection"
        lowerBound="1" eType="#//VSVSAnalysisInspectionReview" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testPlatformRequirementsSection"
        lowerBound="1" eType="#//VSVSTestPlatformRequirements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalInformationSection"
        lowerBound="1" eType="#//VSVSAdditionalInformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="svsFigures" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DAbstractFigure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="svsTables" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DAbstractTable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSInstantiableSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DInstantiableSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="svsInstatiableSubsections"
        upperBound="-1" eType="#//VSVSInstantiableSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSIntroduction" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="svsInstatiableSubsections"
        lowerBound="1" upperBound="-1" eType="#//VSVSInstantiableSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSApplicableDocuments" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocuments" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DApplicableDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSReferenceDocuments" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocuments" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DReferenceDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTermsDefinitionsAbbreviations" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1"
        eType="#//VSVSTerm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//VSVSDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abbreviations" upperBound="-1"
        eType="#//VSVSAbbreviation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSAbstractBriefDescription" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DRun"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTerm" eSuperTypes="#//VSVSAbstractBriefDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSDefinition" eSuperTypes="#//VSVSAbstractBriefDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSAbbreviation" eSuperTypes="#//VSVSAbstractBriefDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSFixedSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="svsInstatiableSubsections"
        upperBound="-1" eType="#//VSVSInstantiableSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSSoftwareOverview" eSuperTypes="#//VSVSFixedSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTaskIdentification" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskCriteria" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuresToBeTested" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuresNotToBeTested"
        lowerBound="1" eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testPassFailCriteria" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemsCanNotBeValidated"
        lowerBound="1" eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manuallyAutoGeneratedCode"
        lowerBound="1" eType="#//VSVSFixedSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTestingSpecificationDesign" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testDesigns" lowerBound="1"
        upperBound="-1" eType="#//VSVSTestDesign" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTestDesign" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuresToBeTested" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="approachRefinements" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTestCases" eSuperTypes="vdm.ecore#//VValidationDocumentFixedGroup ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCases" lowerBound="1"
        upperBound="-1" eType="#//VSVSTestCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTestCase" eSuperTypes="vdm.ecore#//VValidationDocumentAbstractItem ../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passFailCriteria" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentalNeeds" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialConstraints" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceDependencies"
        lowerBound="1" eType="#//VSVSFixedSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTestProcedures" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testProcedures" lowerBound="1"
        upperBound="-1" eType="#//VSVSTestProcedure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTestProcedure" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doc.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purpose" lowerBound="1"
        eType="#//VSVSFixedSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procedureSteps" lowerBound="1"
        eType="#//VSVSProcedureSteps" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testScript" eType="#//VSVSFixedSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCase" lowerBound="1"
        upperBound="-1" eType="#//VSVSTestCase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSProcedureSteps">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" lowerBound="1" upperBound="1900"
        eType="#//VSVSProcedureStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VSVSStepMode">
    <eLiterals name="continuous"/>
    <eLiterals name="manual" value="1"/>
    <eLiterals name="concurrent" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSProcedureStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1" eType="#//VSVSStepMode"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="replays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prev_step_idref" eType="#//VSVSProcedureStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_idref_from_prev_step"
        eType="#//VSVSStepOutput"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
        eType="#//VSVSStepInputs" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" eType="#//VSVSStepOutputs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialPackets" eType="#//VSVSStepSpecialPackets"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concurrent_steps" eType="#//VSVSStepConcurrentSteps"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepInputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_3" upperBound="-1"
        eType="#//VSVSStepInputLevel3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_2" upperBound="-1"
        eType="#//VSVSStepInputLevel2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_1" upperBound="-1"
        eType="#//VSVSStepInputLevel1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_level_0" upperBound="-1"
        eType="#//VSVSStepInputLevel0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VSVSStepUnit">
    <eLiterals name="miliseconds"/>
    <eLiterals name="seconds" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VSVSStepCheckmode">
    <eLiterals name="all"/>
    <eLiterals name="allunsorted" value="1"/>
    <eLiterals name="any" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepOutputs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkmode" lowerBound="1"
        eType="#//VSVSStepCheckmode" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid_time_interval_value"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid_time_interval_unit"
        lowerBound="1" eType="#//VSVSStepUnit" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_3" upperBound="-1"
        eType="#//VSVSStepOutputLevel3" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_2" upperBound="-1"
        eType="#//VSVSStepOutputLevel2" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_1" upperBound="-1"
        eType="#//VSVSStepOutputLevel1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_level_0" upperBound="-1"
        eType="#//VSVSStepOutputLevel0" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepSpecialPackets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enable" upperBound="-1"
        eType="#//VSVSStepEnableDisable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disable" upperBound="-1"
        eType="#//VSVSStepEnableDisable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enable_print" upperBound="-1"
        eType="#//VSVSStepEnableDisable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disable_print" upperBound="-1"
        eType="#//VSVSStepEnableDisable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepEnableDisable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VSVSStepYesNo">
    <eLiterals name="yes"/>
    <eLiterals name="no" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepConcurrentSteps">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStep" lowerBound="1"
        eType="#//VSVSStepNextStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concurrent_step" lowerBound="1"
        upperBound="-1" eType="#//VSVSStepConcurrentStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepNextStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConcurrent" lowerBound="1"
        eType="#//VSVSStepYesNo" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepConcurrentStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepInput">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay_unit" lowerBound="1"
        eType="#//VSVSStepUnit" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepInputLevel3" eSuperTypes="#//VSVSStepInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level3" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3_to_level2" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_to_level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepInputLevel2" eSuperTypes="#//VSVSStepInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level2" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_to_level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepInputLevel1" eSuperTypes="#//VSVSStepInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_to_level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepInputLevel0" eSuperTypes="#//VSVSStepInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="app_to_level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/export.ecore#//TMTCIFExportExport"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepOutput" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ifRef" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepOutputLevel3" eSuperTypes="#//VSVSStepOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level3_from_level2" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/import.ecore#//TMTCIFImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_from_level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/import.ecore#//TMTCIFImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_from_level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/import.ecore#//TMTCIFImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepOutputLevel2" eSuperTypes="#//VSVSStepOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level2_from_level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/import.ecore#//TMTCIFImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_from_level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/import.ecore#//TMTCIFImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepOutputLevel1" eSuperTypes="#//VSVSStepOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level1_from_level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/import.ecore#//TMTCIFImportImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepOutputLevel0" eSuperTypes="#//VSVSStepOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/format.ecore#//TMTCIFFormatFormat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level0_filter" lowerBound="1"
        eType="#//VSVSStepFilter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSStepFilter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apply_def_filter" lowerBound="1"
        eType="#//VSVSStepYesNo" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_filter" eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/filter.ecore#//TMTCIFFilterFilter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSAnalysisInspectionReview" eSuperTypes="#//VSVSFixedSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSTestPlatformRequirements" eSuperTypes="#//VSVSFixedSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VSVSAdditionalInformation" eSuperTypes="#//VSVSFixedSection"/>
</ecore:EPackage>
