<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tdm" nsURI="http://srg.aut.uah.es/micobs/svm/tdm" nsPrefix="micobs.svm">
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocument" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
        eType="#//VTraceableDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" lowerBound="1"
        upperBound="-1" eType="#//VTraceableDocumentAbstractGroup" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentAbstractGroup" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//VTraceableDocumentAbstractItem" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentFixedGroup" abstract="true"
      eSuperTypes="#//VTraceableDocumentAbstractGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentInstantiableGroup"
      abstract="true" eSuperTypes="#//VTraceableDocumentAbstractGroup ../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj"/>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentAbstractItem" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationMethod" lowerBound="1"
        eType="#//VValidationMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//VTraceableDocumentAbstractGroup"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentItem" upperBound="-1"
        eType="#//VTraceableDocumentAbstractItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VValidationMethod">
    <eLiterals name="Analysis" literal="A"/>
    <eLiterals name="Inspection" value="1" literal="I"/>
    <eLiterals name="Testing" value="2" literal="T"/>
    <eLiterals name="Review" value="3" literal="R"/>
    <eLiterals name="ModelSimulation" value="4" literal="MS"/>
    <eLiterals name="WalkThrough" value="5" literal="WT"/>
    <eLiterals name="CrossReading" value="6" literal="CR"/>
    <eLiterals name="DeskChecking" value="7" literal="DC"/>
  </eClassifiers>
</ecore:EPackage>
