<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tdm" nsURI="http://srg.aut.uah.es/micobs/svm/tdm" nsPrefix="svm">
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocument" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonPackageElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" lowerBound="1"
        upperBound="-1" eType="#//VTraceableDocumentAbstractSection" derived="true"
        eOpposite="#//VTraceableDocumentAbstractSection/document"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
        eType="#//VTraceableDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" lowerBound="1"
        upperBound="-1" eType="#//VTraceableDocumentAbstractGroup" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentAbstractSection" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" lowerBound="1"
        upperBound="-1" eType="#//VTraceableDocumentAbstractGroup" derived="true"
        eOpposite="#//VTraceableDocumentAbstractGroup/section"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//VTraceableDocument" eOpposite="#//VTraceableDocument/sections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentFixedSection" abstract="true"
      eSuperTypes="#//VTraceableDocumentAbstractSection"/>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentInstantiableSection"
      abstract="true" eSuperTypes="#//VTraceableDocumentAbstractSection ../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj"/>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentAbstractGroup" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1" upperBound="-1"
        eType="#//VTraceableDocumentItem" derived="true" eOpposite="#//VTraceableDocumentItem/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" lowerBound="1"
        eType="#//VTraceableDocumentAbstractSection" eOpposite="#//VTraceableDocumentAbstractSection/groups"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentFixedGroup" abstract="true"
      eSuperTypes="#//VTraceableDocumentAbstractGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentInstantiableGroup"
      abstract="true" eSuperTypes="#//VTraceableDocumentAbstractGroup ../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj"/>
  <eClassifiers xsi:type="ecore:EClass" name="VTraceableDocumentItem" abstract="true"
      eSuperTypes="../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verificationMethod" lowerBound="1"
        eType="#//VVerificationMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//VTraceableDocumentAbstractGroup"
        eOpposite="#//VTraceableDocumentAbstractGroup/items"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VVerificationMethod">
    <eLiterals name="Analysis"/>
    <eLiterals name="Inspection" value="1"/>
    <eLiterals name="Testing" value="2"/>
    <eLiterals name="Review" value="3"/>
    <eLiterals name="ModelSimulation" value="4"/>
    <eLiterals name="WalkThrough" value="5"/>
    <eLiterals name="CrossReading" value="6"/>
    <eLiterals name="DeskChecking" value="7"/>
  </eClassifiers>
</ecore:EPackage>
