<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testsetup" nsURI="http://srg.aut.uah.es/micobs/svm/testsetup"
    nsPrefix="micobs.svm">
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupDocument" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DDocumentTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tbcsTbdsSection" eType="#//VTestSetupTBCsTBDs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocumentsSection"
        lowerBound="1" eType="#//VTestSetupApplicableDocuments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocumentsSection"
        lowerBound="1" eType="#//VTestSetupReferenceDocuments" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" lowerBound="1"
        eType="#//VTestSetupInterfacesSection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" eType="#//VTestSetupPacketConfigurationsSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" eType="#//VTestSetupActionsSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionsOverVariables" eType="#//VTestSetupActionsOverVariablesSection"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" lowerBound="1"
        eType="#//VTestSetupScenariosSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupTBCsTBDs" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tbcs" upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DTBC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tbds" upperBound="-1" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DTBD"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupApplicableDocuments" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicableDocuments" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DApplicableDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupReferenceDocuments" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceDocuments" upperBound="-1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DReferenceDocument"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupInterfacesSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" lowerBound="1"
        upperBound="-1" eType="#//VTestSetupInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DRun"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tcHeader" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/tcheader.ecore#//TMTCIFTCHeader"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tmHeader" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/tmheader.ecore#//TMTCIFTMHeader"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupPacketConfigurationsSection"
      eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packetConfigurations" lowerBound="1"
        upperBound="-1" eType="#//VTestSetupPacketConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupPacketConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DRun"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupActionsSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//VTestSetupAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VTestSetupActionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VTestSetupActionType">
    <eLiterals name="instruction" literal="instruction"/>
    <eLiterals name="tmtc_checking" value="1" literal="tmtc_checking"/>
    <eLiterals name="checking" value="2" literal="checking"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupActionsOverVariablesSection"
      eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionsOverVariable" lowerBound="1"
        upperBound="-1" eType="#//VTestSetupActionOverVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupActionOverVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VTestSetupActionOverVariableType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VTestSetupActionOverVariableType">
    <eLiterals name="reset" literal="reset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupScenariosSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DFixedSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" lowerBound="1"
        upperBound="-1" eType="#//VTestSetupScenarioSection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupScenarioSection" eSuperTypes="../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DInstantiableSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/scenario.ecore#//TMTCIFScenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedInterface" lowerBound="1"
        upperBound="-1" eType="#//VTestSetupSupportedInterface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedConfiguration"
        upperBound="-1" eType="#//VTestSetupSelectedConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedAction" upperBound="-1"
        eType="#//VTestSetupAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedActionOverVariable"
        upperBound="-1" eType="#//VTestSetupSupportedActionOverVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../es.uah.aut.srg.micobs.doctpl/model/doctpl.ecore#//DBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VTestSetupConfigurationStatus">
    <eLiterals name="not_set" literal="not_set"/>
    <eLiterals name="off" value="1" literal="off"/>
    <eLiterals name="on" value="2" literal="on"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupSupportedInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        eType="#//VTestSetupInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioInterface" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/scenario.ecore#//TMTCIFScenarioInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupSelectedConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//VTestSetupPacketConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultFilterStatus" lowerBound="1"
        eType="#//VTestSetupConfigurationStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPrintStatus" lowerBound="1"
        eType="#//VTestSetupConfigurationStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTestSetupSupportedActionOverVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionOverVariable" lowerBound="1"
        eType="#//VTestSetupActionOverVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioVariable" lowerBound="1"
        eType="ecore:EClass ../../es.uah.aut.srg.tmtcif/model/scenario.ecore#//TMTCIFScenarioVariable"/>
  </eClassifiers>
</ecore:EPackage>
