<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vdm" nsURI="http://srg.aut.uah.es/micobs/svm/vdm" nsPrefix="micobs.svm">
  <eClassifiers xsi:type="ecore:EClass" name="VValidationDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
        eType="ecore:EClass tdm.ecore#//VTraceableDocument"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" lowerBound="1"
        upperBound="-1" eType="#//VValidationDocumentAbstractGroup" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VValidationDocumentAbstractGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//VValidationDocumentAbstractItem" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doc" lowerBound="1" eType="#//VValidationDocument"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VValidationDocumentFixedGroup" eSuperTypes="#//VValidationDocumentAbstractGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="VValidationDocumentInstantiableGroup"
      eSuperTypes="#//VValidationDocumentAbstractGroup ../../es.uah.aut.srg.micobs/model/common.ecore#//MCommonReferenceableObj"/>
  <eClassifiers xsi:type="ecore:EClass" name="VValidationDocumentAbstractItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//VValidationDocumentAbstractGroup"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validatingItem" lowerBound="1"
        upperBound="-1" eType="ecore:EClass tdm.ecore#//VTraceableDocumentAbstractItem"/>
  </eClassifiers>
</ecore:EPackage>
