/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.micobs.svm.lang.tmtemplate.parser.antlr;

import com.google.inject.Inject;
import es.uah.aut.srg.micobs.svm.lang.tmtemplate.parser.antlr.internal.InternalTMTEMPLATEParser;
import es.uah.aut.srg.micobs.svm.lang.tmtemplate.services.TMTEMPLATEGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TMTEMPLATEParser extends AbstractAntlrParser {

	@Inject
	private TMTEMPLATEGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTMTEMPLATEParser createParser(XtextTokenStream stream) {
		return new InternalTMTEMPLATEParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "VTMTemplate";
	}

	public TMTEMPLATEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TMTEMPLATEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
