/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.micobs.svm.lang.tmtemplate.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TMTEMPLATEUiModule extends AbstractTMTEMPLATEUiModule {

	public TMTEMPLATEUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
