/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.micobs.svm.lang.tmtemplate;

import org.eclipse.xtext.naming.IQualifiedNameConverter;

import es.uah.aut.srg.micobs.xtext.MICOBSQualifiedNameProvider.MICOBSDefaultNameConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TMTEMPLATERuntimeModule extends AbstractTMTEMPLATERuntimeModule {

	//added MICOBS qualifier (using :: instead of . for segments) for allowing using . in ref. names
	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return MICOBSDefaultNameConverter.class;
	}
}
