/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.micobs.svm.lang.tmtemplate;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TMTEMPLATERuntimeModule extends AbstractTMTEMPLATERuntimeModule {
}
