/**
 * Copyright (c) 2019 UAH Space Research Group.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 * 
 * Contributors:
 *     SRG Team - Initial API and implementation
 */
package es.uah.aut.srg.micobs.svm.svs;

import es.uah.aut.srg.micobs.doctpl.doc.DFixedSection;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VSVS Task Identification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getTaskCriteria <em>Task Criteria</em>}</li>
 *   <li>{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getFeaturesToBeTested <em>Features To Be Tested</em>}</li>
 *   <li>{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getFeaturesNotToBeTested <em>Features Not To Be Tested</em>}</li>
 *   <li>{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getTestPassFailCriteria <em>Test Pass Fail Criteria</em>}</li>
 *   <li>{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getItemsCanNotBeValidated <em>Items Can Not Be Validated</em>}</li>
 *   <li>{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getManuallyAutoGeneratedCode <em>Manually Auto Generated Code</em>}</li>
 * </ul>
 *
 * @see es.uah.aut.srg.micobs.svm.svs.svsPackage#getVSVSTaskIdentification()
 * @model
 * @generated
 */
public interface VSVSTaskIdentification extends DFixedSection {
	/**
	 * Returns the value of the '<em><b>Task Criteria</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Task Criteria</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Task Criteria</em>' containment reference.
	 * @see #setTaskCriteria(VSVSFixedSection)
	 * @see es.uah.aut.srg.micobs.svm.svs.svsPackage#getVSVSTaskIdentification_TaskCriteria()
	 * @model containment="true" required="true"
	 * @generated
	 */
	VSVSFixedSection getTaskCriteria();

	/**
	 * Sets the value of the '{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getTaskCriteria <em>Task Criteria</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Task Criteria</em>' containment reference.
	 * @see #getTaskCriteria()
	 * @generated
	 */
	void setTaskCriteria(VSVSFixedSection value);

	/**
	 * Returns the value of the '<em><b>Features To Be Tested</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Features To Be Tested</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Features To Be Tested</em>' containment reference.
	 * @see #setFeaturesToBeTested(VSVSFixedSection)
	 * @see es.uah.aut.srg.micobs.svm.svs.svsPackage#getVSVSTaskIdentification_FeaturesToBeTested()
	 * @model containment="true" required="true"
	 * @generated
	 */
	VSVSFixedSection getFeaturesToBeTested();

	/**
	 * Sets the value of the '{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getFeaturesToBeTested <em>Features To Be Tested</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Features To Be Tested</em>' containment reference.
	 * @see #getFeaturesToBeTested()
	 * @generated
	 */
	void setFeaturesToBeTested(VSVSFixedSection value);

	/**
	 * Returns the value of the '<em><b>Features Not To Be Tested</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Features Not To Be Tested</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Features Not To Be Tested</em>' containment reference.
	 * @see #setFeaturesNotToBeTested(VSVSFixedSection)
	 * @see es.uah.aut.srg.micobs.svm.svs.svsPackage#getVSVSTaskIdentification_FeaturesNotToBeTested()
	 * @model containment="true" required="true"
	 * @generated
	 */
	VSVSFixedSection getFeaturesNotToBeTested();

	/**
	 * Sets the value of the '{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getFeaturesNotToBeTested <em>Features Not To Be Tested</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Features Not To Be Tested</em>' containment reference.
	 * @see #getFeaturesNotToBeTested()
	 * @generated
	 */
	void setFeaturesNotToBeTested(VSVSFixedSection value);

	/**
	 * Returns the value of the '<em><b>Test Pass Fail Criteria</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Test Pass Fail Criteria</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Test Pass Fail Criteria</em>' containment reference.
	 * @see #setTestPassFailCriteria(VSVSFixedSection)
	 * @see es.uah.aut.srg.micobs.svm.svs.svsPackage#getVSVSTaskIdentification_TestPassFailCriteria()
	 * @model containment="true" required="true"
	 * @generated
	 */
	VSVSFixedSection getTestPassFailCriteria();

	/**
	 * Sets the value of the '{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getTestPassFailCriteria <em>Test Pass Fail Criteria</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Test Pass Fail Criteria</em>' containment reference.
	 * @see #getTestPassFailCriteria()
	 * @generated
	 */
	void setTestPassFailCriteria(VSVSFixedSection value);

	/**
	 * Returns the value of the '<em><b>Items Can Not Be Validated</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Items Can Not Be Validated</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Items Can Not Be Validated</em>' containment reference.
	 * @see #setItemsCanNotBeValidated(VSVSFixedSection)
	 * @see es.uah.aut.srg.micobs.svm.svs.svsPackage#getVSVSTaskIdentification_ItemsCanNotBeValidated()
	 * @model containment="true" required="true"
	 * @generated
	 */
	VSVSFixedSection getItemsCanNotBeValidated();

	/**
	 * Sets the value of the '{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getItemsCanNotBeValidated <em>Items Can Not Be Validated</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Items Can Not Be Validated</em>' containment reference.
	 * @see #getItemsCanNotBeValidated()
	 * @generated
	 */
	void setItemsCanNotBeValidated(VSVSFixedSection value);

	/**
	 * Returns the value of the '<em><b>Manually Auto Generated Code</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Manually Auto Generated Code</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Manually Auto Generated Code</em>' containment reference.
	 * @see #setManuallyAutoGeneratedCode(VSVSFixedSection)
	 * @see es.uah.aut.srg.micobs.svm.svs.svsPackage#getVSVSTaskIdentification_ManuallyAutoGeneratedCode()
	 * @model containment="true" required="true"
	 * @generated
	 */
	VSVSFixedSection getManuallyAutoGeneratedCode();

	/**
	 * Sets the value of the '{@link es.uah.aut.srg.micobs.svm.svs.VSVSTaskIdentification#getManuallyAutoGeneratedCode <em>Manually Auto Generated Code</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Manually Auto Generated Code</em>' containment reference.
	 * @see #getManuallyAutoGeneratedCode()
	 * @generated
	 */
	void setManuallyAutoGeneratedCode(VSVSFixedSection value);

} // VSVSTaskIdentification
