/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.micobs.svm.lang.tmtemplate.ui;

import com.google.inject.Injector;
import es.uah.aut.srg.micobs.svm.editor.tmtemplate.ui.internal.TmtemplateActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TMTEMPLATEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TmtemplateActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TmtemplateActivator.getInstance().getInjector(TmtemplateActivator.ES_UAH_AUT_SRG_MICOBS_SVM_LANG_TMTEMPLATE_TMTEMPLATE);
	}
	
}
