/*
 * generated by Xtext 2.10.0
 */
package es.uah.aut.srg.micobs.svm.lang.tmtemplate.ide.contentassist.antlr;

import com.google.inject.Inject;
import es.uah.aut.srg.micobs.svm.lang.tmtemplate.ide.contentassist.antlr.internal.InternalTMTEMPLATEParser;
import es.uah.aut.srg.micobs.svm.lang.tmtemplate.services.TMTEMPLATEGrammarAccess;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class TMTEMPLATEParser extends AbstractContentAssistParser {

	@Inject
	private TMTEMPLATEGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalTMTEMPLATEParser createParser() {
		InternalTMTEMPLATEParser result = new InternalTMTEMPLATEParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVTMTemplateAccess().getAlternatives_5(), "rule__VTMTemplate__Alternatives_5");
					put(grammarAccess.getTMTCIFFieldValueAccess().getAlternatives(), "rule__TMTCIFFieldValue__Alternatives");
					put(grammarAccess.getTMTCIFFieldValueRawAccess().getValueAlternatives_2_0(), "rule__TMTCIFFieldValueRaw__ValueAlternatives_2_0");
					put(grammarAccess.getVTMTemplateAccess().getGroup(), "rule__VTMTemplate__Group__0");
					put(grammarAccess.getVTMTemplateAccess().getGroup_5_0(), "rule__VTMTemplate__Group_5_0__0");
					put(grammarAccess.getVTMTemplateAccess().getGroup_5_0_1(), "rule__VTMTemplate__Group_5_0_1__0");
					put(grammarAccess.getVTMTemplateFieldAccess().getGroup(), "rule__VTMTemplateField__Group__0");
					put(grammarAccess.getTMTCIFFieldValueRawAccess().getGroup(), "rule__TMTCIFFieldValueRaw__Group__0");
					put(grammarAccess.getTMTCIFFieldValueFileAccess().getGroup(), "rule__TMTCIFFieldValueFile__Group__0");
					put(grammarAccess.getTMTCIFFieldValueEnumAccess().getGroup(), "rule__TMTCIFFieldValueEnum__Group__0");
					put(grammarAccess.getVTMTemplateAccess().getNameAssignment_2(), "rule__VTMTemplate__NameAssignment_2");
					put(grammarAccess.getVTMTemplateAccess().getTmOutputAssignment_4(), "rule__VTMTemplate__TmOutputAssignment_4");
					put(grammarAccess.getVTMTemplateAccess().getFieldsAssignment_5_0_1_1(), "rule__VTMTemplate__FieldsAssignment_5_0_1_1");
					put(grammarAccess.getVTMTemplateFieldAccess().getFieldRefAssignment_2(), "rule__VTMTemplateField__FieldRefAssignment_2");
					put(grammarAccess.getVTMTemplateFieldAccess().getValueAssignment_4(), "rule__VTMTemplateField__ValueAssignment_4");
					put(grammarAccess.getTMTCIFFieldValueRawAccess().getValueAssignment_2(), "rule__TMTCIFFieldValueRaw__ValueAssignment_2");
					put(grammarAccess.getTMTCIFFieldValueFileAccess().getFilenameAssignment_2(), "rule__TMTCIFFieldValueFile__FilenameAssignment_2");
					put(grammarAccess.getTMTCIFFieldValueEnumAccess().getEnumRefAssignment_2(), "rule__TMTCIFFieldValueEnum__EnumRefAssignment_2");
					put(grammarAccess.getTMTCIFFieldValueEnumAccess().getValueRefAssignment_4(), "rule__TMTCIFFieldValueEnum__ValueRefAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalTMTEMPLATEParser typedParser = (InternalTMTEMPLATEParser) parser;
			typedParser.entryRuleVTMTemplate();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TMTEMPLATEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TMTEMPLATEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
